// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_GetImageCd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Say                  string   `protobuf:"bytes,1,opt,name=say,proto3" json:"say,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

type Request struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Response struct {
	Error    string `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	ErrorMsg string `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	//Pix []uint8
	//图片的结构元素
	Pix []byte `protobuf:"bytes,3,opt,name=Pix,proto3" json:"Pix,omitempty"`
	//Stride int
	//图片的跨度
	Stride int64 `protobuf:"varint,4,opt,name=Stride,proto3" json:"Stride,omitempty"`
	//Rect Rectangle
	//type Rectangle struct {
	//	Min, Max Point
	//}
	Min                  *Response_Point `protobuf:"bytes,5,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  *Response_Point `protobuf:"bytes,6,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *Response) GetPix() []byte {
	if m != nil {
		return m.Pix
	}
	return nil
}

func (m *Response) GetStride() int64 {
	if m != nil {
		return m.Stride
	}
	return 0
}

func (m *Response) GetMin() *Response_Point {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *Response) GetMax() *Response_Point {
	if m != nil {
		return m.Max
	}
	return nil
}

//type Point struct {
//	X, Y int
//}
//坐标
//用来代替Point
type Response_Point struct {
	X                    int64    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Point) Reset()         { *m = Response_Point{} }
func (m *Response_Point) String() string { return proto.CompactTextString(m) }
func (*Response_Point) ProtoMessage()    {}
func (*Response_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2, 0}
}

func (m *Response_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Point.Unmarshal(m, b)
}
func (m *Response_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Point.Marshal(b, m, deterministic)
}
func (m *Response_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Point.Merge(m, src)
}
func (m *Response_Point) XXX_Size() int {
	return xxx_messageInfo_Response_Point.Size(m)
}
func (m *Response_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Point proto.InternalMessageInfo

func (m *Response_Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Response_Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.GetImageCd.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetImageCd.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetImageCd.Response")
	proto.RegisterType((*Response_Point)(nil), "go.micro.srv.GetImageCd.Response.Point")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4b, 0xfb, 0x30,
	0x14, 0xc7, 0x7f, 0x59, 0xd6, 0x76, 0xbf, 0xe7, 0x0e, 0x12, 0x44, 0x43, 0x87, 0x50, 0xeb, 0xc1,
	0x9e, 0x22, 0xcc, 0x93, 0x67, 0x19, 0xe2, 0xa1, 0x30, 0x32, 0x84, 0xed, 0x22, 0x44, 0xfb, 0x28,
	0x01, 0xdb, 0xd4, 0xa4, 0x93, 0x7a, 0xf4, 0x3f, 0x97, 0x66, 0x9d, 0x9e, 0x54, 0x3c, 0xf5, 0xfb,
	0xe9, 0xcb, 0x37, 0xef, 0x7d, 0x5f, 0x60, 0xd6, 0x58, 0xd3, 0x9a, 0x4b, 0xec, 0x54, 0xd5, 0x3c,
	0xe3, 0xfe, 0x2b, 0xfc, 0x5f, 0x76, 0x52, 0x1a, 0x51, 0xe9, 0x27, 0x6b, 0x84, 0xb3, 0xaf, 0xe2,
	0x16, 0xdb, 0xbb, 0x4a, 0x95, 0x78, 0x53, 0xa4, 0x33, 0x88, 0x72, 0x74, 0x4e, 0x95, 0xc8, 0x0e,
	0x81, 0x3a, 0xf5, 0xc6, 0x49, 0x42, 0xb2, 0xff, 0xb2, 0x97, 0xe9, 0x29, 0x44, 0x12, 0x5f, 0xb6,
	0xe8, 0x5a, 0xc6, 0x60, 0x7c, 0xbf, 0xd5, 0xc5, 0x50, 0xf5, 0x3a, 0x7d, 0x1f, 0xc1, 0x44, 0xa2,
	0x6b, 0x4c, 0xed, 0x90, 0x1d, 0x41, 0xb0, 0xb0, 0xd6, 0xd8, 0xe1, 0xc4, 0x0e, 0x58, 0x0c, 0x13,
	0x2f, 0x72, 0x57, 0xf2, 0x91, 0x2f, 0x7c, 0x72, 0xdf, 0x6f, 0xa9, 0x3b, 0x4e, 0x13, 0x92, 0x4d,
	0x65, 0x2f, 0xd9, 0x31, 0x84, 0xab, 0xd6, 0xea, 0x02, 0xf9, 0x38, 0x21, 0x19, 0x95, 0x03, 0xb1,
	0x6b, 0xa0, 0xb9, 0xae, 0x79, 0x90, 0x90, 0xec, 0x60, 0x7e, 0x21, 0xbe, 0xc9, 0x22, 0xf6, 0xb3,
	0x88, 0xa5, 0xd1, 0x75, 0x2b, 0x7b, 0x8f, 0xb7, 0xaa, 0x8e, 0x87, 0x7f, 0xb5, 0xaa, 0x2e, 0x3e,
	0x87, 0xc0, 0x13, 0x9b, 0x02, 0x59, 0xfb, 0x58, 0x54, 0x92, 0x75, 0x4f, 0x1b, 0x9f, 0x85, 0x4a,
	0xb2, 0x99, 0x3f, 0x40, 0xb4, 0xd8, 0x6d, 0x9a, 0xad, 0x00, 0xbe, 0x6e, 0x64, 0xc9, 0x0f, 0xbd,
	0xfc, 0x4a, 0xe3, 0xb3, 0x5f, 0xa7, 0x49, 0xff, 0x3d, 0x86, 0xfe, 0xfd, 0xae, 0x3e, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x53, 0xf3, 0x95, 0x71, 0xde, 0x01, 0x00, 0x00,
}
